### ISSUE TITLE
RuntimeException: Failed to read awsconfiguration.json please check that it is correctly formed.

### ISSUE THREAD

**Issue by ilikepi63** [scientifichackers/flutter_cognito_plugin#16]
Until a few hours ago where I made a pub get to refresh my dependencies, this was working fine. I currently have my awsconfiguration.json file within the res/raw directory inside of my android file when running 'flutter run' within the console, it throws the following error: 

```I/flutter (16510): RuntimeException: Failed to read awsconfiguration.json please check that it is correctly formed.
I/flutter (16510): java.lang.RuntimeException: Failed to read awsconfiguration.json please check that it is correctly formed.
I/flutter (16510):      at com.amazonaws.mobile.config.AWSConfiguration.readInputJson(AWSConfiguration.java:125)
I/flutter (16510):      at com.amazonaws.mobile.config.AWSConfiguration.<init>(AWSConfiguration.java:109)
I/flutter (16510):      at com.amazonaws.mobile.config.AWSConfiguration.<init>(AWSConfiguration.java:94)
I/flutter (16510):      at com.amazonaws.mobile.config.AWSConfiguration.<init>(AWSConfiguration.java:71)
I/flutter (16510):      at com.amazonaws.mobile.client.AWSMobileClient.initialize(AWSMobileClient.java:434)
I/flutter (16510):      at com.pycampers.flutter_cognito_plugin.Cognito.initialize(Cognito.kt:22)
I/flutter (16510):      at java.lang.reflect.Method.invoke(Native Method)
I/flutter (16510):      at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$createPluginScaffold$1$$special$$inlined$let$lambda$1.invoke(PluginScaffoldPlugin.kt:75)
I/flutter (16510):      at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$createPluginScaffold$1$$special$$inlined$let$lambda$1.invoke(Unknown
I/flutter (16510): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (16510): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
I/flutter (16510): <asynchronous suspension>                            
I/flutter (16510): #2      Cognito.invokeMethodWithChannel (package:flutter_cognito_plugin/flutter_cognito_plugin.dart:70:30)
I/flutter (16510): #3      Cognito.invokeMethod (package:flutter_cognito_plugin/flutter_cognito_plugin.dart:86:12)
I/flutter (16510): #4      Cognito.initialize (package:flutter_cognito_plugin/flutter_cognito_plugin.dart:107:11)
I/flutter (16510): #5      MyAppState.doLoad (package:flutter_cognito_plugin_example/main.dart:30:29)
I/flutter (16510): #6      MyAppState.initState (package:flutter_cognito_plugin_example/main.dart:54:5)
I/flutter (16510): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
I/flutter (16510): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (16510): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (16510): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
```

This then stops initialization within the app and once the user tries to install the apk on an android device, they get a MissingPluginException from flutter. This also occurs currently in the example app when being installed.

**Comment by ilikepi63** [comment]
Issue resolved. 

Had to wipe the cache of the android emulator.
