### ISSUE TITLE
Error when implementing Hosted UI

### ISSUE THREAD

**Issue by Andranjo97** [scientifichackers/flutter_cognito_plugin#30]
Hello flutter cognito plugin team! Would you mind helping me with something? When I want to call a hosted UI using 
```
Cognito.showSignIn(
    identityProvider: "google",
    scopes: ["email", "openid"],
);
```
I get this error:
```
D/AWSMobileClient(18123): getHostedUIJSON: Failed to read config
D/AWSMobileClient(18123): java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.amazonaws.mobile.config.AWSConfiguration.optJsonObject(java.lang.String)' on a null object reference
D/AWSMobileClient(18123): 	at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSONFromJSON(AWSMobileClient.java:641)
D/AWSMobileClient(18123): 	at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:660)
D/AWSMobileClient(18123): 	at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:655)
D/AWSMobileClient(18123): 	at com.amazonaws.mobile.client.AWSMobileClient._showSignIn(AWSMobileClient.java:2679)
D/AWSMobileClient(18123): 	at com.amazonaws.mobile.client.AWSMobileClient.showSignIn(AWSMobileClient.java:2659)
D/AWSMobileClient(18123): 	at com.pycampers.flutter_cognito_plugin.Cognito.showSignIn(Cognito.kt:236)
D/AWSMobileClient(18123): 	at java.lang.reflect.Method.invoke(Native Method)
D/AWSMobileClient(18123): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$createPluginScaffold$1$$special$$inlined$let$lambda$1.invoke(PluginScaffoldPlugin.kt:78)
D/AWSMobileClient(18123): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$createPluginScaffold$1$$special$$inlined$let$lambda$1.invoke(Unknown Source:0)
D/AWSMobileClient(18123): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt.catchErrors(PluginScaffoldPlugin.kt:172)
D/AWSMobileClient(18123): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt.catchErrors(PluginScaffoldPlugin.kt:179)
D/AWSMobileClient(18123): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$createMethodWrapper$2$1.invoke(PluginScaffoldPlugin.kt:132)
D/AWSMobileClient(18123): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$createMethodWrapper$2$1.invoke(Unknown Source:0)
D/AWSMobileClient(18123): 	at com.pycampers.plugin_scaffold.DoAsync.doInBackground(PluginScaffoldPlugin.kt:287)
D/AWSMobileClient(18123): 	at com.pycampers.plugin_scaffold.DoAsync.doInBackground(PluginScaffoldPlugin.kt:281)
D/AWSMobileClient(18123): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
D/AWSMobileClient(18123): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D/AWSMobileClient(18123): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
D/AWSMobileClient(18123): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D/AWSMobileClient(18123): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D/AWSMobileClient(18123): 	at java.lang.Thread.run(Thread.java:919)
```
and then
```
E/flutter (18123): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(java.lang.Exception, showSignIn called with HostedUI options in awsconfiguration.json, java.lang.Exception: showSignIn called with HostedUI options in awsconfiguration.json
E/flutter (18123): 	at com.amazonaws.mobile.client.AWSMobileClient$23.run(AWSMobileClient.java:2684)
E/flutter (18123): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
E/flutter (18123): 	at java.lang.Thread.run(Thread.java:919)
E/flutter (18123): )
E/flutter (18123): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (18123): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:163:17)
E/flutter (18123): <asynchronous suspension>
E/flutter (18123): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:337:12)
E/flutter (18123): #3      Cognito.invokeMethodWithChannel (package:flutter_cognito_plugin/flutter_cognito_plugin.dart:75:36)
E/flutter (18123): #4      Cognito.invokeMethod (package:flutter_cognito_plugin/flutter_cognito_plugin.dart:92:12)
E/flutter (18123): #5      Cognito.showSignIn (package:flutter_cognito_plugin/flutter_cognito_plugin.dart:294:11)
```
And, my awsconfig.json is as follows:
```
{
    "IdentityManager": {
        "Default": {}
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "XX-XXXX-X_abcd1234",
            "AppClientId": "XXXXXXXX",
            "AppClientSecret": "XXXXXXXXX",
            "Region": "XX-XXXX-X"
        }
    },
  "Auth": {
    "Default": {
      "OAuth": {
        "WebDomain": "XXX.auth.ap-south-1.amazoncognito.com",
        "AppClientId": "XXXXXXXX",
        "SignInRedirectURI": "myapp://callback",
        "SignOutRedirectURI": "myapp://signout",
        "Scopes": ["email"]
      }
    }
  }
}
```
Am I doing something wrong?

**Comment by JayDev43** [comment]
I'm getting the same error as this as well

**Comment by JayDev43** [comment]
Think I figured this out. Its not clear from the initial documentation on setup, but I found it in the example. I think you need to call the below method before trying to signin
 
```
await Cognito.initialize();
```

**Comment by devxpy** [comment]
I thought it was clear from the [example](https://github.com/scientifichackers/flutter_cognito_plugin/blob/9f69c3a04687faa197dfcdb680b7a0aa7264b4d3/example/lib/main.dart#L44) app that this is needed. If you can suggest a better place for it, I'd be happy to add it.

**Comment by JayDev43** [comment]
> I thought it was clear from the [example](https://github.com/scientifichackers/flutter_cognito_plugin/blob/9f69c3a04687faa197dfcdb680b7a0aa7264b4d3/example/lib/main.dart#L44) app that this is needed. If you can suggest a better place for it, I'd be happy to add it.

Agreed. In the example app it was obvious this was needed. For me I originally went through the setup in the readme and my point was that from that alone, it was not obvious.
