### ISSUE TITLE
unexpected character in attributes field

### ISSUE THREAD

**Issue by nyck33** [scientifichackers/flutter_cognito_plugin#47]
```
/flutter ( 9995): #12     TapGestureRecognizer.handleTapUp (package:flutter/src
I/flutter ( 9995): FormatException: Unexpected character (at character 1)
I/flutter ( 9995): nobu.kim66@gmail.com
I/flutter ( 9995): ^
I/flutter ( 9995): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
I/flutter ( 9995): #1      _ChunkedJsonParser.parseNull (dart:convert-patch/convert_patch.dart:996:7)
I/flutter ( 9995): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:879:22)
I/flutter ( 9995): #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
I/flutter ( 9995): #4      JsonDecoder.convert (dart:convert/json.dart:506:36)
I/flutter ( 9995): #5      JsonCodec.decode (dart:convert/json.dart:157:41)
I/flutter ( 9995): #6      jsonDecode (dart:convert/json.dart:96:10)
I/flutter ( 9995): #7      MyAppState.signUp.<anonymous closure> (package:flutter_cognito_plugin_example/main.dart:166:61)
I/flutter ( 9995): #8      MyAppState.onPressWrapper.wrapper (package:flutter_cognito_plugin_example/main.dart:109:26)
I/flutter ( 9995): #9      MyAppState.onPressWrapper.wrapper (package:flutter_cognito_plugin_example/main.dart:102:12)
I/flutter ( 9995): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
I/flutter ( 9995): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
I/flutter ( 9995): #12     TapGestureRecognizer.handleTapUp (package:flutter/src

```

**Comment by nyck33** [comment]
I left username blank, typed in a password that meets the requirements in password field and email in attribute field as that is the default setting to sign users up by email on my cognito identity pool/user pool.
